### ISSUE TITLE
Is there a way to get the image via CLI once generated?

### ISSUE THREAD

**Issue by ktynski** [ja-pa/midjourney-cli#1]

**Comment by ja-pa** [comment]
Not yet, but it's something I'm working on.

**Comment by ja-pa** [comment]
In mean time, this could be helpful https://github.com/timmc/midjourney-history-sync/blob/master/sync.sh#L35

**Comment by ja-pa** [comment]
There is now argument -l which can be used to list created images. It takes some time to sync it with discord bot. And you can then download images by -d argument. https://github.com/ja-pa/midjourney-cli/commit/42273bde16896c67beef2ee538989e01c165f5e3
